### PR TITLE
Consolidate optional and required dependencies

### LINKED ISSUE #40: build configuration macros are not in use
Stuff like `HAVE_SAMPLERATE` and `HAVE_OPUS` is not being set at the moment, leading to all optional features being disabled.

### PR DESCRIPTION
**Pull request by dvzrv**
Remove the requirement for celt by removing all sections added by `HAVE_CELT` (celt is superseded by opus).
Use libsamplerate by default by removing the preprocessor macros for `HAVE_SAMPLERATE`, but not the sections defined by them.
Properly setup opus to be an optional requirement for `jack_netsource` and state this in the README (also add information on alsa-lib only being optional).
Properly detect and use `ppoll()` (`HAVE_PPOLL`) if available.

Fixes #40

### CODE REVIEW

**Comment by falkTX** [comment]
What about `HAVE_CELT`?

**Comment by falkTX** [comment]
This is also wrong.
Either libsamplerate is an optional dependency and we need a conditional macro (so it cannot always be set) or make libsamplerate required and remove the macro check from the code.

**Comment by dvzrv** [comment]
> This is also wrong. Either libsamplerate is an optional dependency and we need a conditional macro (so it cannot always be set) or make libsamplerate required and remove the macro check from the code.

Then I'd rather opt for removing the macro, as it makes no sense to me to have such a finely granular optional dependency (libsamplerate is required by alsa_{in,out}.c as well).

If we want to do the same for opus, should we just remove the celt dependency while at it? It does not seem to make sense to keep it and only adds unnecessary complexity.

**Review by falkTX — CHANGES_REQUESTED** [review]
Looks good, but since we are removing celt there are a few extra things that should go as well in the net code:
1. Usage of `factor` variable
2. Usage of 'f' CLI arg
3. Checks for `bitdepth == 100` (was a hack used for celt mode detection)

**Comment by dvzrv** [comment]
> Looks good, but since we are removing celt there are a few extra things that should go as well in the net code:
> 
>     1. Usage of `factor` variable
> 
>     2. Usage of 'f' CLI arg
> 
>     3. Checks for `bitdepth == 100` (was a hack used for celt mode detection)

Please see whether https://github.com/jackaudio/jack-example-tools/pull/44/commits/b9e328d64181121541815005ce46853db469bc68 is what you had in mind

**Review by falkTX — CHANGES_REQUESTED** [review]
1 tiny change to go! just remove a single line, thanks!

**Pull request merged**
